export type NewsItem = {
  title: string;
  href: string;
  source?: string;
  kind: "article" | "pdf";
  image?: string;
  imageAlt?: string;
  excerpt?: string;
};

export const newsItems: NewsItem[] = [
  {
    title: "Building Our Foundation: The 2025 Annual Report",
    href: "/imported/docs/Final-Cornerstone-Craftsman-Annual-Report-Bound-Document-3-2.pdf",
    source: "Cornerstone Craftsman",
    kind: "pdf",
    image: "/imported/images/2026-05-Annual-Report-Cover-Page.png",
    imageAlt: "2025 Annual Report",
  },
  {
    title: "Alexandria nonprofit Cornerstone Craftsman receives $10K donation, 100 laptops for apprentices",
    href: "https://www.alxnow.com/2025/12/11/alexandria-nonprofit-cornerstone-craftsman-receives-10k-donation-100-laptops-for-apprentices/",
    source: "ALXnow",
    kind: "article",
  },
  {
    title: "Cornerstone Craftsman Recognized As 'Rising Star' at Alexandria Chamber of Commerce Best in Business Awards",
    href: "/imported/docs/CC-BinB-News-Release-10.24.25.pdf",
    source: "News release",
    kind: "pdf",
    image: "/imported/images/2025-10-CC-BinB.jpeg",
    imageAlt: "CC BinB",
  },
  {
    title: "Breaking the Cycle: How Cornerstone Craftsman Builds a Skilled Workforce",
    href: "https://electricalalliance.org/2026/07/20/breaking-the-cycle-how-cornerstone-craftsman-builds-a-skilled-workforce/",
    source: "Electrical Alliance",
    kind: "article",
    image: "/imported/images/2026-08-IBEW_Washington-DC_CheMaiah-Francis_0823_0014A_SM-702x526-1.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Alexandria nonprofit Cornerstone Craftsman builds new futures by teaching trades",
    href: "https://www.alxnow.com/2025/11/18/alexandria-nonprofit-cornerstone-craftsman-builds-new-futures-by-teaching-trades/",
    source: "ALXnow",
    kind: "article",
    image: "/imported/images/2025-11-5254fad9-554f-4af1-8cbd-f457a69fc9e2-1536x1024-1.jpeg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Alexandria Chamber announces finalists for 2025 Best in Business Awards",
    href: "https://www.alxnow.com/2025/09/24/alexandria-chamber-announces-finalists-for-2025-best-in-business-awards/",
    source: "ALXnow",
    kind: "article",
    image: "/imported/images/2025-10-CC-BinB.jpeg",
    imageAlt: "CC BinB",
  },
  {
    title: "Roberto Gomez invited to speak at AEDP annual impact meeting",
    href: "https://www.alxnow.com/2025/10/07/alexandria-economic-development-partnership-celebrates-major-wins-in-new-carlisle-office-space/",
    source: "ALXnow",
    kind: "article",
    image: "/imported/images/2025-10-DSC02446.jpg",
    imageAlt: "DSC02446",
  },
  {
    title: "Cornerstone Craftsman’s pre-apprentice program provides paths for city youth",
    href: "https://alextimes.com/local-news/cornerstone-craftsman-apprentice-program-alexandria/",
    source: "Alexandria Times",
    kind: "article",
    image: "/imported/images/2025-09-IMG_6910.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Meet the ACPS Partners: Cornerstone Craftsman - Opening Doors to Future Success",
    href: "https://www.acps.k12.va.us/about-us/express/stories/~board/express-2025/post/meet-the-acps-partners-cornerstone-craftsman-opening-doors-to-future-success",
    source: "ACPS",
    kind: "article",
    image: "/imported/images/2025-09-IMG_6553.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Roberto Gomez’s Blueprint on Building Futures and Changing Lives Through Cornerstone Craftsman",
    href: "https://alexandriaecon.org/roberto-gomezs-blueprint-on-building-futures-and-changing-lives-through-cornerstone-craftsman/",
    source: "Alexandria Economic Development Partnership",
    kind: "article",
    image: "/imported/images/2025-09-Cornerstone-Craftsman-2-1-1280x854.jpg.webp",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Roberto Gomez, CYFCC Champions of Children Awards Winner",
    href: "https://myemail.constantcontact.com/July-2025-Newsletter.html?soid=1102583984660&aid=EpYbUzk__fo",
    source: "CYFCC newsletter",
    kind: "article",
    image: "/imported/images/2025-08-Screenshot-2025-08-13-011437.png",
    imageAlt: "Published clipping from the original In the News page",
  },
  {
    title: "D.C. Local Partners With Nonprofit to Introduce Teens to Trades",
    href: "https://ibew.org/electrical_worker/local-26-cornerstone-craftsman/",
    source: "IBEW Electrical Worker",
    kind: "article",
    image: "/imported/images/2025-08-202508-circuits-lu26-cc-building-2.webp",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Alexandria nonprofits receive $110,000 in Community Foundation grants",
    href: "https://www.alxnow.com/2025/04/18/alexandria-nonprofits-receive-110000-in-community-foundation-grants/",
    source: "ALXnow",
    kind: "article",
    image: "/imported/images/2025-03-Cornerstone.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Cornerstone Craftsman Celebrates Grand Opening of New Alexandria Location",
    href: "https://thezebra.org/2025/02/28/cornerstone-craftsman-grand-opening/",
    source: "The Zebra",
    kind: "article",
    image: "/imported/images/2025-03-2ccab804-img_7188-1.jpg",
    imageAlt: "2ccab804 img 7188 1",
  },
  {
    title: "Nonprofit offering mentorship to local teens opens new Eisenhower HQ",
    href: "https://www.alxnow.com/2025/03/03/notes-nonprofit-offering-mentorship-to-local-teens-opens-new-eisenhower-hq/",
    source: "ALXnow",
    kind: "article",
    image: "/imported/images/2025-03-Cornerstone.jpg",
    imageAlt: "Published photograph from the original In the News page",
    excerpt:
      "Zebra reported that Cornerstone Craftsman, a new nonprofit dedicated to teaching Alexandria teens trade skills, celebrated a grand opening on Friday of its new Eisenhower Avenue home.",
  },
  {
    title: "A New Perspective on Alexandria: Insights from Mayor on Challenges, Growth, and Diversity",
    href: "/imported/docs/Northern-Virginia-Magazine-November-2024.pdf",
    source: "Northern Virginia Magazine, November 2024",
    kind: "pdf",
    image: "/imported/images/2024-11-NorthernVirginia.png",
    imageAlt: "Northern Virginia Magazine clipping",
  },
  {
    title: "Nonprofit dedicated to teaching kids trade skills",
    href: "https://www.alxnow.com/2025/01/15/nonprofit-dedicated-to-teaching-kids-trade-skills-opening-new-eisenhower-facility-next-month/",
    source: "ALXnow",
    kind: "article",
    image: "/imported/images/2024-04-20230319_1122151-scaled.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Alexandria Gang Prevention Community Task Force",
    href: "/imported/docs/Alexandria-Gange-Prevention-Community-Task-Force-Newsletter-7.24.24.pdf",
    source: "Newsletter, July 24, 2024",
    kind: "pdf",
    image: "/imported/images/2024-11-20230416_110531-scaled.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Alexandria Times, We’ve Impacted Generations",
    href: "/imported/docs/Alexandria-Times-Weve-Impacted-Generations-5.30.24.pdf",
    source: "Alexandria Times, May 30, 2024",
    kind: "pdf",
    image: "/imported/images/2024-11-alexandria-times.png",
    imageAlt: "Alexandria Times clipping",
  },
  {
    title: "Roberto Gomez, 40 Under 40 Honoree",
    href: "/imported/docs/Past-40-Under-40-Honorees-2.pdf",
    source: "Published clipping",
    kind: "pdf",
    image: "/imported/images/2024-11-40-under-40.png",
    imageAlt: "40 Under 40 honoree clipping",
  },
  {
    title: "Apprenticeship Helps Teen Gain Employment",
    href: "https://www.fairfaxtimes.com/positive_vibes/apprenticeship-helps-teen-gain-employment/article_d760ab20-c12c-11ee-b78c-070028060636.html",
    source: "Fairfax Times",
    kind: "article",
    image: "/imported/images/2024-11-20230723_130848-scaled.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
  {
    title: "Cornerstone Craftsman: Constructing Futures",
    href: "https://actheogony.com/7097/spotlight/cornerstone-craftsman-constructing-futures/",
    source: "AC Theogony",
    kind: "article",
    image: "/imported/images/2024-11-unnamed-5-1200x675-1.jpg",
    imageAlt: "Published photograph from the original In the News page",
  },
];
